// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezfpqftlpdmwhrnqrpmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZnBxZnRscGRtd2hybnFycG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjkwMTEsImV4cCI6MjA2NDUwNTAxMX0.Rt622M30dH3Bz2X2h9MCvPLmi6d9gHOZ6Pq310RhSVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);