// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsqislzgcrkdijnsjrmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzcWlzbHpnY3JrZGlqbnNqcm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjM5NjgsImV4cCI6MjA2Mzg5OTk2OH0.x8ONquVBCD13FzSLq8Mt3jMsp75lkzY70vzFndZSmO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);